version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Airtable
  AIRTABLE_ACCESS_TOKEN: token
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id:  "de-nyc-taxi"
    private_key_id: "48039e316e28a8d76a9be9a862213ef38047e7f1"
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDARy1DNulHUp2v\nORH6maOOASur1kqsJvGA4qdB9JLxzDJEQRHpq1SGBjCrbr3QkOMKmB6NEaZmKj8F\n96+ae29RlNzj6D7rOib/yokMZX9pxggElVnezrkAWswlRHmDcUfR+23bs17dN540\nITep79ExFjGMkMUtOLWPCfBhoh7weBEOZnAiO+PJWUcQhDvtqMM/c/qF+YIu6M0P\nVOh6jotlTcqrIQ5XVROI8MUGM1mbtFQufqhaRAwCauojlqtAG5MEPct7Vwgxe6qh\nFouFmEk3Ufg8Y+TFoSsniVGPMEabxAIyazJjHmE4o+3em4e+p9wmP3yPFCxdHf1k\nK35+5FZhAgMBAAECggEABy7Bfe4fscE1exWz2mYsihdOGn8IpBICWduy/s+UQQHC\nlkfN/lTJoAYRgbNDK6GLRwU0DaCtVB9bjQKvJc4FnwkOEATIJkEHsuzNyM+ZKQoz\nmM7myrVzNhRY5ZgqEo3D7o/+Dxkjao/I0k60BcjxH2x3pmDEFN02SbpyfIXcslk2\nenXK317hlXVUsTCitxjvcwEJ04mHuOklvCZ9oja1T3UpNwWtwN38ZQxOMxFRt9aR\nP0a0+F1+iN+/L1A91nXWN6DqbwGiTQ2XO/6u/pgBT8hZuEu6BjCoS+x/XUe6QQfc\n3B3K/Gzvvi8shgmsOCCBwkFczBfmJZqKSoqu6dPLiQKBgQD9UZhToh/npthfTj7h\nC/aOqcTho1BfLGD/u053kldPmWDAPrbmHAbUDylRLz6Gq4hhD6iOQyjIIgauYRT/\nTXawHz5xjqkhRki5//7HxxlAlh2/zO7ZqMnSJ+lWmBqt4jAUzzk7i/gW0oRJLJma\nzjBbYW+y8bDIEeeJly16NynZNQKBgQDCUC7RxP49dE1WaDiSoHtxFWpGOaQ2XHSH\nZLKVJ0T23m/+gEJFPpeKSmOL9LQ5K/1WmTQDW0ngy25aW2j+x4s2tZ0+FSzH16xq\n//HTMPIsSsvg8uwYdCvf+E8r370X9Qwjw9o0GC57Sg5H3nsO5IFGTiYsNavMJaLC\nz46NR9iZ/QKBgDo/7wUcPLXp+ctAlNjvBU0c4Lb59NtNuyhTC+IW9pjJLiRGx4v2\nWeOdcOTINlqFSyD2ls3Px6rtmBe1HzzttSMerB80rNOH8+VBZnbN45KkckbOewX1\n+CKpJtDQvSHK5z+BvylgMDYfRmgFJ3UfgKMirqq5ROtcop9S8hQuZyMZAoGAHZA7\nf1jcYZc3SQU0TkKyZUMf1y1f6ZFpfUv5y62c1X6ERZFYA9cBEV4+BQYnAWfK9Ij8\nm+IgvF3XHVI5CEJt0NYS5WYtWP5cUi88qKgSwGBk4oWzHAlYv4u05/TzfRigTzS2\nFyTytXlP8OlNibeEX6D2N9W2nKnBOKiBhMdAkjUCgYBu7s1vT4hmwyUXThlYQ4gO\ndCOY7SNgnxr9MY/UrtJK0cCdSeL6gKS1PK5g9XWere6KOAohxNT39rxtICSiocFS\nCO9+eENwRJKhVsErEM2DWakmD5yrRuYUhUVykG93HG1dr5EVEH9UebJfUnt4O8JH\nL7Dqn7YVdv2R5M1g0pvr2w==\n-----END PRIVATE KEY-----\n"
    client_email: "nyctaxi-dataengineering-projec@de-nyc-taxi.iam.gserviceaccount.com"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/nyctaxi-dataengineering-projec%40de-nyc-taxi.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
